project:
  type: website
  execute-dir: project
  # (output-dir omitted â€” defaults to _site)

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
      - href: about.qmd
        text: "About Team"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
