project:
  type: website
  execute-dir: project
  
execute:
  freeze: auto
  echo: false
  eval: true
  code-fold: false

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Introduction"
      - href: data_cleaning.qmd
        text: "Data Cleaning & Exploration"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: SKILL_GAP_ANALYSIS.QMD
        text: "Skill Gap Analysis"
      - href: "ML.QMD"
        text: "Machine Learning Methods"
      - href: nlp_methods.qmd
        text: "NLP Methods"

format:
  html:
    theme: cosmo
    toc: true
    code-tools: false