project:
  type: website
  
execute:
  freeze: auto
  echo: false
  eval: true
  code-fold: false

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_cleaning.qmd
        text: "Data Cleaning & Exploration"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: SKILL_GAP_ANALYSIS.QMD
        text: "Skill Gap Analysis"
      - href: ML.QMD
        text: "Machine Learning Methods"
      - href: NLP.QMD
        text: "Natural Language Processing Methods"

format:
  html:
    theme: cosmo
    toc: true
    code-tools: false